<?php

namespace booksBundle\Repository;

/**
 * LivreOccasionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreOccasionRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall(){
        $query=$this->getEntityManager()->createQuery("Select l from booksBundle:LivreOccasion l where l.treated='0'");
        return $query->getResult();
    }
    public function myfindetat($etat){
        $query=$this->getEntityManager()->createQuery("Select l from booksBundle:LivreOccasion l where l.etatLivre='$etat' AND l.treated='0'");
        return $query->getResult();
    }
    public function findByCategorieDql($categorie)
    {
        $qd=$this->getEntityManager()
            ->createQuery("SELECT l FROM booksBundle:LivreOccasion l WHERE l.categorie.nomCategorie LIKE :categorie")
            ->setParameter(':categorie',$categorie);
        return $qd->getResult();
    }
    public function myfindt(){
        $query=$this->getEntityManager()->createQuery("Select l from booksBundle:LivreOccasion l where l.treated='1'");
        return $query->getResult();
    }

}
